[package]
name = "rdbs_interface"
version = "0.1.0"
edition = "2024"

[dependencies]
gio = "0.20.9"
iced = { version = "0.13.1", features = ["tokio"] }
iced_aw = "0.12.2"
log = "0.4.27"
log4rs = "1.3.0"
pg_escape = "0.1.1"
thiserror = "2.0.12"
tokio = { version = "1.44.2", features = ["full"] }
tokio-postgres = "0.7.13"
